image:
- Visual Studio 2017
- Ubuntu1804

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 25

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%

install:
- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -B build -S .
- sh: cmake -B build -S .

- cmake --build build --parallel --target install

test_script:
- cd build
- ctest --parallel --output-on-failure

artifacts:
- path: build/rpncalc.exe
  name: WindowsExecutable

- path: build/rpncalc
  name: LinuxExecutable

deploy:
  description: 'Executables for Fortran 2018 RPN Calculator'
  draft: true
  provider: GitHub
  artifact: build/rpncalc.exe
  on:
    branch: master
    APPVEYOR_REPO_TAG: true