image:
- Visual Studio 2017
- Ubuntu1804

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 25

build: off

init:
- cmd: set PATH=%MINGW_DIR%;%PATH%

install:
- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -B $APPVEYOR_BUILD_FOLDER/build
- sh: cmake -B $APPVEYOR_BUILD_FOLDER/build

- cmake --build $APPVEYOR_BUILD_FOLDER/build --target install

test_script:
- cd $APPVEYOR_BUILD_FOLDER/build
- ctest --output-on-failure

artifacts:
- path: $APPVEYOR_BUILD_FOLDER/build/rpncalc.exe