language: c
fast_finish: true
sudo: required

os:
  - linux
  - osx

env: FC=gfortran-5

dist: xenial
group: travis_latest

git:
  depth: 3

addons:
  apt:
    packages: gfortran-5
    
before_install:
  - mkdir -p ~/.local/bin
  - ln -s /usr/bin/gfortran-6 ~/.local/bin/gfortran
  - export PATH="$HOME/.local/bin/:$PATH"

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true > /dev/null;
      brew link --overwrite gcc > /dev/null;
      export FC=gfortran;
    fi

install:
  - cd bin
  - cmake ../src
  - cmake --build . --target install

script: 
  - ctest -V

