language: c
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

os:
  - linux
  - osx

env: FC=gfortran-5

addons:
  apt:
    packages: gfortran-5
    
before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
      export FC=gfortran;
    fi

install:
  - cd bin
  - cmake ../src
  - cmake --build . --target install

script: 
  - ctest -V

