language: c
fast_finish: true

os:
  - linux

env: FC=gfortran-6

group: travis_latest

git:
  depth: 3

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages: gfortran-6
    
before_install:
  - mkdir -p ~/.local/bin
  - ln -s /usr/bin/gfortran-6 ~/.local/bin/gfortran
  - export PATH="$HOME/.local/bin/:$PATH"

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true > /dev/null;
      brew link --overwrite gcc > /dev/null;
    fi

script: 
    - make

