language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages: gfortran
    
matrix:
  include:
  - os: linux
  - os: osx
    before_install:
    - brew install gcc > /dev/null
  - os: windows
    language: sh
    install: 
    - cd bin
    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ../src
    - cmake --build . --target install

install:
- cd bin
- cmake ../src
- cmake --build . --target install

script: ctest --output-on-failure

