language: minimal
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    packages: gfortran

before_install: pip install meson

install:
- meson build
- meson install -C build

script: meson test -C build
