name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset make
    - run: cmake --build build
    - run: ctest --preset default


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset makewin
    - run: cmake --build build
    - run: ctest --preset default
