name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_cmake.yml"
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9


  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cinst -y ninja

    - run: ctest -S setup.cmake -VV
