name: ci_cmake

env:
  CTEST_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update
        sudo apt install ninja-build

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

  windows:
    needs: linux
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -G "MinGW Makefiles"
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default

    - name: .exe for release
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: rpncalc.exe
        path: build/rpncalc.exe
