name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        pip install cmake
        sudo apt -yq update
        sudo apt install -yq --no-install-recommends gfortran

    - run: cmake -B build
      env:
        FC: gfortran

    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_CMake_Testlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build

  windows:
    if: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - run: cinst -y ninja

    - run: cmake -B build -G Ninja
      env:
        FC: gfortran

    - run: cmake --build build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_CMake_Testlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest -V
      working-directory: build