name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux_macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest]
        gcc_version: ['9', '10', '11']
        include:
        - os: macos-latest


    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install pytest
      run: python -m pip install numpy scipy pytest

    - name: install gfortran (linux)
      if: runner.os == 'Linux'
      run: sudo apt install gfortran-${{ matrix.gcc_version }}

    - name: install gfortran
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - uses: actions/checkout@v3

    - run: cmake --preset default

    - run: cmake --build --preset default --parallel

    - run: ctest --preset default


  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install pytest
      run: python -m pip install numpy scipy pytest

    - uses: actions/checkout@v3

    - run: cmake --preset default -G Ninja
    - run: cmake --build --preset default
    - run: ctest --preset default

    - name: .exe for release
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: rpncalc.exe
        path: build/rpncalc.exe
