name: ci_cmake

env:
  cmake_version: '3.21.0-rc3'

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # FIXME: till CMake 3.21 is released, we need to use the following
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: |
        pip install cmakeutils ninja
        python -m cmakeutils.cmake_setup ${cmake_version} --prefix ${HOME}/.local
        echo "${HOME}/.local/cmake-${cmake_version}-linux-x86_64/bin" >> $GITHUB_PATH

    - run: cmake --preset default
    - run: cmake --build build
    - run: ctest --preset default --output-junit test-results.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-results.xml

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake --preset default -G "MinGW Makefiles"
    - run: cmake --build build
    - run: ctest --preset default

    - name: .exe for release
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: rpncalc.exe
        path: build/rpncalc.exe
