name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux_macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      matrix:
        os: [ubuntu-22.04]
        gcc_version: [9, 10, 11]
        include:
        - os: macos-latest
          gcc_version: 11

    env:
      FC: gfortran-${{ matrix.gcc_version }}

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install pytest
      run: python -m pip install numpy scipy pytest

    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default


  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      CMAKE_GENERATOR: Ninja

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install pytest
      run: python -m pip install numpy scipy pytest

    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default

    - name: .exe for release
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: rpncalc.exe
        path: build/rpncalc.exe
