name: ci_meson

on:
  push:
    paths:
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install pytest
      run: python -m pip install numpy scipy pytest

    - name: install Meson
      run: pip install meson ninja

    - uses: actions/checkout@v2

    - run: meson setup build
    - run: meson test -C build -v

# saving CI resources
  # macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'

  #   - run: pip install meson ninja

  #   - run: meson setup build
  #     env:
  #       FC: gfortran-11

  #   - run: meson test -C build -v


  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'

  #   - run: pip install meson ninja

  #   - run: meson setup build

  #   - run: meson test -C build -v
